In [7]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}

In [8]:
def predict(dp):
    if dp['maxvibration']> 100:
        return 13
    else:
        return 0.33

In [9]:
predict(dp1)

0.33

In [10]:
predict(dp2)

0.33

In [11]:
predict(dp3)

13

In [12]:
predict(dp4)

13

In [70]:
w1 = 0.30
w2 = 0
w3 = 0
w4 = 13/3412.0

def mlpredict(dp):
    return w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']

In [74]:
mlpredict(dp4)

13.795310668229778

In [102]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'broken': 0}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'broken': 0}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'broken': 1}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'broken': 1}

In [103]:
def predict(dp):
    if dp['maxvibration']> 100:
        return 1
    else:
        return 0

In [104]:
predict(dp1)

0

In [105]:
predict(dp2)

0

In [106]:
predict(dp3)

1

In [107]:
predict(dp4)

1

In [113]:
import math

def sigmoid(x):
    return 1/(1+math.exp(-x))

In [119]:
w1 = 0.30
w2 = 0
w3 = 0
w4 = 13/3412.0

def mlpredict(dp):
    return 1 if sigmoid(w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']) > 0.7 else 0

In [124]:
mlpredict(dp4)

1

In [188]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}

In [189]:
dp1

{'asperity': 0.32,
 'maxtemp': 35,
 'maxvibration': 12,
 'mintemp': 35,
 'partno': 100}

In [198]:
x1 = np.array([1] + [v for k, v in dp1.items()] [1:-1])
x2 = np.array([1] + [v for k, v in dp2.items()] [1:-1])
x3 = np.array([1] + [v for k, v in dp3.items()] [1:-1])
x4 = np.array([1] + [v for k, v in dp4.items()] [1:-1])

In [197]:
x1

array([  1.  ,  35.  ,   0.32,  35.  ])

In [199]:
w_layer1 = np.random.rand(4)

def neuron(x):
    return sigmoid(x.dot(w_layer1))

In [200]:
neuron(x1)

0.9999999999559348

In [201]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [202]:
w_layer1 = np.random.rand(4,4)

def layer1(x):
    return sigmoid(x.dot(w_layer1))

In [203]:
x = np.array([x1,x2,x3,x4])

In [204]:
x

array([[  1.  ,  35.  ,   0.32,  35.  ],
       [  1.  ,  35.  ,   0.34,  46.  ],
       [  1.  ,  46.  ,  12.42,  56.  ],
       [  1.  ,  48.  ,  13.43,  58.  ]])

In [205]:
layer1(x)

array([[ 0.99998882,  1.        ,  1.        ,  1.        ],
       [ 0.99999931,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ]])

In [206]:
w_layer2 = np.random.rand(4,4)

def layer2(x):
    return sigmoid(x.dot(w_layer2))

In [207]:
layer2(layer1(x))

array([[ 0.78965544,  0.86723112,  0.93535789,  0.95621991],
       [ 0.78965579,  0.86723191,  0.93535818,  0.9562201 ],
       [ 0.78965582,  0.86723196,  0.93535819,  0.95622011],
       [ 0.78965582,  0.86723196,  0.93535819,  0.95622011]])